---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-web-app-deployment
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-web-app
  template:
    metadata:
      labels:
        app: java-web-app
    spec:
      containers:
      - name: maven-web-app-container
        image: demoak93/maven-web-application:b9bc087f
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: maven-web-app-service
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: java-web-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007 # This port will be used to access the service from outside the cluster
