name: CI Build and Push to Quay.io

on:
  push:
    branches:
      - master # Make sure this matches your repository's branch name

env:
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  QUAY_REPO: mavenwebapp # This is the name of your repository on Quay.io

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ env.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker buildx build --push \
            --tag quay.io/${{ env.QUAY_USERNAME }}/${{ env.QUAY_REPO }}:latest \
            .
