name: CI Build and Push to Quay.io

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Quay.io
        run: echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin

      - name: Build and Push Docker image to Quay.io
        run: |
          docker build --tag quay.io/${{ secrets.QUAY_USERNAME }}/mavenwebapp:latest .
          docker push quay.io/${{ secrets.QUAY_USERNAME }}/mavenwebapp:latest
