name: CI Build and Push to Quay.io

on:
  push:
    branches:
      - master # Adjust this branch name if your main branch is different

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the application code to build the image
      - name: Checkout application repository
        uses: actions/checkout@v4
        with:
          repository: AKdevops-World/maven-web-application

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      # Step 2: Build and push the image with a dynamic tag
      - name: Build and Push Docker image to Quay.io
        run: |
          docker buildx build --push \
            --tag quay.io/demoak93/mavenwebapp:latest \
            --tag quay.io/demoak93/mavenwebapp:${{ github.sha }} \
            .

      # Step 3: Checkout the GitOps repository
      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: AKdevops-World/mavenwebapp-gitops
          token: ${{ secrets.GIT_OPS_TOKEN }}
          path: gitops_repo

      # Step 4: Update the image tag in the deployment file
      # The correct path is now `gitops_repo/deployment.yaml`
      - name: Update image tag in deployment.yaml
        run: |
          sed -i 's|image: quay.io/demoak93/mavenwebapp:.*|image: quay.io/demoak93/mavenwebapp:${{ github.sha }}|' gitops_repo/deployment.yaml

      # Step 5: Commit and push the changes to the GitOps repository
      - name: Commit and push updated deployment
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cd gitops_repo # Change to the GitOps repository directory
          git add deployment.yaml
          git commit -m "chore: Update mavenwebapp image tag to ${{ github.sha }}"
          git push
