name: CI Build and Push to Quay.io

on:
  push:
    branches:
      - master # Make sure this matches your repository's branch name

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and Push Docker image to Quay.io
        run: |
          docker buildx build --push \
            --tag quay.io/demoak93/mavenwebapp:latest \
            .
