name: CI Build and Push to Quay.io

on:
  push:
    branches:
      - main # This workflow will run every time you push to the 'main' branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest # The type of machine to run the job on

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and Push Docker image to Quay.io
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: quay.io/${{ secrets.QUAY_USERNAME }}/mavenwebapp:latest
