name: CI Build and Push to Quay.io

on:
  push:
    branches:
      - master # Ensure this matches your branch name

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Quay.io (HARDCODED)
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: demoak93+mavenwebapp # Replace with your full robot username
          password: CRA9OCSOMZJ1RNZCHBSOMNBPMSJVY4F7UO3WPQJ1UFZUBF92B3SDATJ0V2Z4HJA2 # Replace with your actual token

      - name: Build and Push Docker image to Quay.io (HARDCODED)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: quay.io/demoak93+mavenwebapp/mavenwebapp:latest # Replace with your full robot username
