name: Build and Push to Quay

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Build with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Log in to Quay.io
      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            quay.io/${{ secrets.QUAY_USERNAME }}/mavenwebapp:latest
            quay.io/${{ secrets.QUAY_USERNAME }}/mavenwebapp:${{ github.sha }}
