name: Build, Push and Update GitOps

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout application repo (this repo)
      - name: Checkout application repo
        uses: actions/checkout@v4

      # Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Build with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Login to Quay.io
      - name: Log in to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Docker image
        run: |
          IMAGE=quay.io/demoak93/mavenwebapp:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      # Checkout GitOps repo
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: AKdevops-World/mavenwebapp-gitops
          token: ${{ secrets.GIT_OPS_PUSHER }}   # PAT secret
          path: gitops

      # Update deployment.yaml (replace only the tag)
      - name: Update deployment.yaml
        run: |
          sed -i "s|\(quay.io/demoak93/mavenwebapp:\).*|\1${GITHUB_SHA}|g" gitops/deployment.yaml

      # Commit and push changes
      - name: Commit and Push changes
        run: |
          cd gitops
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GIT_OPS_PUSHER }}@github.com/AKdevops-World/mavenwebapp-gitops.git
          git add deployment.yaml
          git commit -m "Update image to quay.io/demoak93/mavenwebapp:${GITHUB_SHA}" || echo "No changes to commit"
          git push origin master
