name: Build, Push and Update GitOps

on:
  push:
    branches:
      - main

permissions:
  contents: write   # allow pushing changes to gitops repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout application repo
      - name: Checkout application repo
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Build with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Log in to Quay.io with robot account
      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}   # e.g. demoak93+kubernetes
          password: ${{ secrets.QUAY_PASSWORD }}   # robot account token

      # Build and push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            quay.io/demoak93/mavenwebapp:latest
            quay.io/demoak93/mavenwebapp:${{ github.sha }}

      # Checkout GitOps repo
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: AKdevops-World/mavenwebapp-gitops
          token: ${{ secrets.GITHUB_TOKEN }}   # default token, works for public repo
          path: gitops

      # Update deployment.yaml with new image tag
      - name: Update deployment.yaml
        run: |
          sed -i "s|quay.io/demoak93/mavenwebapp:.*|quay.io/demoak93/mavenwebapp:${{ github.sha }}|g" gitops/deployment.yaml

      # Commit and push changes to GitOps repo
      - name: Commit and Push changes
        run: |
          cd gitops
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add deployment.yaml
          git commit -m "Update image to quay.io/demoak93/mavenwebapp:${{ github.sha }}"
          git push origin master
