name: CI with Docker Build and Push

on:
  push:
    branches:
      - main  # Adjust this to your main branch name if it's different

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # The cache line is optional. If you get a cache error again,
          # you can comment this line out or remove it.
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/maven-web-application:latest
          # Uncomment the line below if you want to also tag with the commit SHA
          # tags: |
          #   ${{ secrets.DOCKERHUB_USERNAME }}/maven-web-application:latest
          #   ${{ secrets.DOCKERHUB_USERNAME }}/maven-web-application:${{ github.sha }}
