name: Build, Push and Update GitOps

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout application repo (this repo)
      - name: Checkout application repo
        uses: actions/checkout@v4

      # Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Build with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Login to Quay.io
      - name: Log in to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Docker image
        run: |
          IMAGE=quay.io/demoak93/mavenwebapp:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      # Checkout GitOps repo (mavenwebapp-gitops)
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: AKdevops-World/mavenwebapp-gitops
          token: ${{ secrets.GIT_OPS_PUSHER }}   # ✅ your PAT secret
          path: gitops

      # Update deployment.yaml with new image
      - name: Update deployment.yaml
        run: |
          sed -i "s|quay.io/demoak93/mavenwebapp:.*|${IMAGE}|g" gitops*
